=== 5A-Informatica-IIS-Silva-Ricci/XML/esercizi/fattura/fattura.dtd
<!ELEMENT fattura (intestazione, tabella, piede)>

<!ELEMENT intestazione (mittente, destinatario)>

<!ELEMENT mittente ()>
<!ATTLIST mittente codice_fiscale CDATA #IMPLIED>
<!ELEMENT destinatario ()>
<!ATTLIST destinatario codice_fiscale CDATA #IMPLIED>

<!ELEMENT tabella (articolo)+>
<!ELEMENT articolo (nome, costo)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT costo (#PCDATA)>

<!ELEMENT piede (totale, totale_iva)>
<!ELEMENT totale (#PCDATA)>
<!ELEMENT totale_iva (#PCDATA)>

=== 5A-Informatica-IIS-Silva-Ricci/XML/esercizi/fattura/fattura.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fattura SYSTEM "fattura.dtd">

<fattura>
    <intestazione>
        <mittente>PMNGLI03</mittente>
        <destinatario>STRLCA03</destinatario>
    </intestazione>
    <tabella>
        <articolo>
            <nome>Libro TPSIT Quinta</nome>
            <costo>18</costo>
        </articolo>
    </tabella>
    <piede>
        <totale>18</totale>
        <totale_iva>23</totale_iva>
    </piede>
</fattura>
